DEVICE: cuda

DATASET:
    BATCH_SIZE: 64
    WORKERS: 2
    FEATURE_PATH:
      IMAGE: image

VOCAB:
  TOKENIZER: null
  MIN_FREQ: 5
  WORD_EMBEDDING: null
  WORD_EMBEDDING_CACHE: null
  BOS_TOKEN: <bos>
  EOS_TOKEN: <eos>
  PAD_TOKEN: <pad>
  UNK_TOKEN: <unk>
  
JSON_PATH:
  TRAIN: train.json
  DEV: dev.json
  TEST: test.json

TRAINING:
  CHECKPOINT_PATH: save
  LEARNING_RATE: 1
  RL_LEARNING_RATE: 0.000005
  WARMUP: 10000
  SCORE: CIDEr
  TRAINING_BEAM_SIZE: 5
  EVALUATING_BEAM_SIZE: 3
  PATIENCE: 5

VISION_EMBEDDING:
  PRETRAINED_NAME: vit
  D_FEATURE: 768
  D_MODEL: 512
  DROPOUT: .1

TEXT_EMBEDDING:
  PRETRAINED_NAME: bert-base-multilingual-uncased
  D_FEATURE: 768
  D_MODEL: 512
  DROPOUT: .1

MODEL: 
  NAME: vit_mbert
  D_MODEL: 512
  DROPOUT: .1
  DECODER:

DECODER:
  D_MODEL: 512
  LAYERS: 3
  LANGUAGE_MODEL: bert-base-multilingual-uncased

ATTENTION:
  HEAD: 8
  D_MODEL: 512
  D_KEY: 64
  D_VALUE: 64
  D_FF: 2048
  D_FEATURE: 2048
  USE_AOA: False
  CAN_BE_STATEFUL: True
  DROPOUT: .1

    TEXT_EMBEDDING:
      ARCHITECTURE: UsualEmbedding
      D_MODEL: 512
      D_EMBEDDING: 300
      WORD_EMBEDDING: null
      WORD_EMBEDDING_CACHE: null
      DROPOUT: 0.1